export interface Trip {
  id: number;
  traveler: string;
  route: string;
  from: string;
  to: string;
  date: string;
  space: string;
  spaceKg: number;
  pricePerKg: number;
  price: string;
  verified: boolean;
  rating: number;
  notes?: string;
}

export const mockTrips: Trip[] = [
  {
    id: 1,
    traveler: "Maria S.",
    route: "Lima → Miami",
    from: "Lima",
    to: "Miami",
    date: "Nov 15, 2024",
    space: "8kg available",
    spaceKg: 8,
    pricePerKg: 15,
    price: "$15/kg",
    verified: true,
    rating: 4.8,
    notes: "Direct flight, can meet at Jorge Chávez airport",
  },
  {
    id: 2,
    traveler: "Carlos R.",
    route: "Miami → Lima",
    from: "Miami",
    to: "Lima",
    date: "Nov 18, 2024",
    space: "12kg available",
    spaceKg: 12,
    pricePerKg: 18,
    price: "$18/kg",
    verified: true,
    rating: 4.9,
    notes: "Regular traveler, flexible meeting point",
  },
  {
    id: 3,
    traveler: "Ana P.",
    route: "Cusco → Miami",
    from: "Cusco",
    to: "Miami",
    date: "Nov 20, 2024",
    space: "5kg available",
    spaceKg: 5,
    pricePerKg: 20,
    price: "$20/kg",
    verified: true,
    rating: 4.7,
    notes: "One stop in Lima, can deliver to Fort Lauderdale area",
  },
  {
    id: 4,
    traveler: "Diego M.",
    route: "Lima → Miami",
    from: "Lima",
    to: "Miami",
    date: "Nov 22, 2024",
    space: "10kg available",
    spaceKg: 10,
    pricePerKg: 16,
    price: "$16/kg",
    verified: false,
    rating: 4.5,
  },
  {
    id: 5,
    traveler: "Sofia L.",
    route: "Miami → Lima",
    from: "Miami",
    to: "Lima",
    date: "Nov 25, 2024",
    space: "6kg available",
    spaceKg: 6,
    pricePerKg: 17,
    price: "$17/kg",
    verified: true,
    rating: 4.9,
    notes: "Experienced traveler, 20+ deliveries",
  },
  {
    id: 6,
    traveler: "Roberto G.",
    route: "Arequipa → Miami",
    from: "Arequipa",
    to: "Miami",
    date: "Nov 28, 2024",
    space: "7kg available",
    spaceKg: 7,
    pricePerKg: 19,
    price: "$19/kg",
    verified: true,
    rating: 4.6,
  },
  {
    id: 7,
    traveler: "Isabel V.",
    route: "Lima → Orlando",
    from: "Lima",
    to: "Orlando",
    date: "Dec 1, 2024",
    space: "15kg available",
    spaceKg: 15,
    pricePerKg: 16,
    price: "$16/kg",
    verified: true,
    rating: 4.8,
    notes: "Can also deliver to Tampa area",
  },
  {
    id: 8,
    traveler: "Miguel A.",
    route: "Miami → Cusco",
    from: "Miami",
    to: "Cusco",
    date: "Dec 3, 2024",
    space: "9kg available",
    spaceKg: 9,
    pricePerKg: 19,
    price: "$19/kg",
    verified: true,
    rating: 4.7,
  },
  {
    id: 9,
    traveler: "Patricia C.",
    route: "Lima → Miami",
    from: "Lima",
    to: "Miami",
    date: "Dec 5, 2024",
    space: "11kg available",
    spaceKg: 11,
    pricePerKg: 15,
    price: "$15/kg",
    verified: true,
    rating: 4.9,
    notes: "Business traveler, monthly trips",
  },
  {
    id: 10,
    traveler: "Fernando H.",
    route: "Fort Lauderdale → Lima",
    from: "Fort Lauderdale",
    to: "Lima",
    date: "Dec 8, 2024",
    space: "8kg available",
    spaceKg: 8,
    pricePerKg: 17,
    price: "$17/kg",
    verified: false,
    rating: 4.4,
  },
];
