export interface UseCaseStep {
  id: number;
  icon: string;
  title: string;
  titleEs: string;
  description: string;
  descriptionEs: string;
  duration?: string;
  durationEs?: string;
}

export interface UseCase {
  id: string;
  title: string;
  titleEs: string;
  description: string;
  descriptionEs: string;
  icon: string;
  gradientClass: string;
  steps: UseCaseStep[];
}

export const useCases: UseCase[] = [
  {
    id: "package-received-miami",
    title: "Package Received in Miami",
    titleEs: "Paquete Recibido en Miami",
    description: "Sender orders online, traveler picks up and delivers to Lima",
    descriptionEs: "Remitente ordena online, viajero recoge y entrega en Lima",
    icon: "ShoppingCart",
    gradientClass: "bg-gradient-to-br from-blue-500/20 via-indigo-500/20 to-purple-500/20",
    steps: [
      {
        id: 1,
        icon: "ShoppingCart",
        title: "Sender orders product online",
        titleEs: "Remitente ordena producto online",
        description: "Order from Amazon, eBay, or any US retailer. Product ships to sender's Miami address.",
        descriptionEs: "Ordena de Amazon, eBay o cualquier minorista de EE.UU. Producto se envía a dirección en Miami del remitente.",
        duration: "1-3 days",
        durationEs: "1-3 días",
      },
      {
        id: 2,
        icon: "MapPin",
        title: "Traveler picks up package",
        titleEs: "Viajero recoge el paquete",
        description: "Traveler coordinates pickup at sender's Miami address or nearby location.",
        descriptionEs: "Viajero coordina recogida en dirección en Miami del remitente o ubicación cercana.",
        duration: "30 min",
        durationEs: "30 min",
      },
      {
        id: 3,
        icon: "Package",
        title: "Package inspection & confirmation",
        titleEs: "Inspección y confirmación del paquete",
        description: "Both parties verify package contents, weight, and condition before travel.",
        descriptionEs: "Ambas partes verifican contenido, peso y condición del paquete antes del viaje.",
        duration: "15 min",
        durationEs: "15 min",
      },
      {
        id: 4,
        icon: "Plane",
        title: "Traveler flies to Lima",
        titleEs: "Viajero vuela a Lima",
        description: "Package travels safely in traveler's luggage with full insurance coverage.",
        descriptionEs: "Paquete viaja seguro en equipaje del viajero con cobertura de seguro completa.",
        duration: "5-8 hours",
        durationEs: "5-8 horas",
      },
      {
        id: 5,
        icon: "Home",
        title: "Delivery to recipient in Lima",
        titleEs: "Entrega a destinatario en Lima",
        description: "Traveler delivers to recipient's address or meets at agreed location.",
        descriptionEs: "Viajero entrega en dirección del destinatario o se reúnen en ubicación acordada.",
        duration: "1-2 hours",
        durationEs: "1-2 horas",
      },
      {
        id: 6,
        icon: "CheckCircle",
        title: "Payment released",
        titleEs: "Pago liberado",
        description: "Recipient confirms delivery, payment released to traveler within 24-48 hours.",
        descriptionEs: "Destinatario confirma entrega, pago liberado al viajero en 24-48 horas.",
        duration: "24-48 hours",
        durationEs: "24-48 horas",
      },
    ],
  },
  {
    id: "store-visit-miami",
    title: "Store Visit in Miami",
    titleEs: "Visita a Tienda en Miami",
    description: "Traveler shops at specific store, purchases item, and delivers to Lima",
    descriptionEs: "Viajero compra en tienda específica y entrega en Lima",
    icon: "Store",
    gradientClass: "bg-gradient-to-br from-green-500/20 via-emerald-500/20 to-teal-500/20",
    steps: [
      {
        id: 1,
        icon: "MessageSquare",
        title: "Sender requests specific item",
        titleEs: "Remitente solicita artículo específico",
        description: "Sender specifies product, store location (Best Buy, Walmart, Target, etc.), and budget.",
        descriptionEs: "Remitente especifica producto, ubicación de tienda (Best Buy, Walmart, Target, etc.) y presupuesto.",
        duration: "15 min",
        durationEs: "15 min",
      },
      {
        id: 2,
        icon: "DollarSign",
        title: "Sender transfers funds",
        titleEs: "Remitente transfiere fondos",
        description: "Sender sends money to traveler via Zelle, Venmo, or PayPal for purchase + delivery fee.",
        descriptionEs: "Remitente envía dinero al viajero vía Zelle, Venmo o PayPal para compra + tarifa de entrega.",
        duration: "Instant",
        durationEs: "Instantáneo",
      },
      {
        id: 3,
        icon: "Store",
        title: "Traveler shops at store",
        titleEs: "Viajero compra en tienda",
        description: "Traveler visits store, purchases item, and sends receipt/photos to sender.",
        descriptionEs: "Viajero visita tienda, compra artículo y envía recibo/fotos al remitente.",
        duration: "1-2 hours",
        durationEs: "1-2 horas",
      },
      {
        id: 4,
        icon: "Package",
        title: "Item packaged for travel",
        titleEs: "Artículo empacado para viaje",
        description: "Traveler ensures item is properly packaged and protected for flight.",
        descriptionEs: "Viajero asegura que artículo esté bien empacado y protegido para vuelo.",
        duration: "30 min",
        durationEs: "30 min",
      },
      {
        id: 5,
        icon: "Plane",
        title: "Traveler flies to Lima",
        titleEs: "Viajero vuela a Lima",
        description: "Item travels safely with full insurance. Traveler provides flight updates.",
        descriptionEs: "Artículo viaja seguro con seguro completo. Viajero proporciona actualizaciones de vuelo.",
        duration: "5-8 hours",
        durationEs: "5-8 horas",
      },
      {
        id: 6,
        icon: "Home",
        title: "Delivery in Lima",
        titleEs: "Entrega en Lima",
        description: "Traveler delivers item to recipient, both parties confirm successful delivery.",
        descriptionEs: "Viajero entrega artículo al destinatario, ambas partes confirman entrega exitosa.",
        duration: "1-2 hours",
        durationEs: "1-2 horas",
      },
    ],
  },
  {
    id: "lima-messenger",
    title: "Lima Messenger Pickup",
    titleEs: "Mensajero en Lima Recoge",
    description: "Traveler delivers to local messenger who handles final delivery",
    descriptionEs: "Viajero entrega a mensajero local quien maneja entrega final",
    icon: "Bike",
    gradientClass: "bg-gradient-to-br from-orange-500/20 via-amber-500/20 to-yellow-500/20",
    steps: [
      {
        id: 1,
        icon: "Package",
        title: "Package received in Miami",
        titleEs: "Paquete recibido en Miami",
        description: "Sender ships package to traveler's Miami address or coordinates pickup.",
        descriptionEs: "Remitente envía paquete a dirección del viajero en Miami o coordina recogida.",
        duration: "1-3 days",
        durationEs: "1-3 días",
      },
      {
        id: 2,
        icon: "Plane",
        title: "Traveler flies with package",
        titleEs: "Viajero vuela con paquete",
        description: "Package travels in traveler's luggage with insurance coverage to Lima.",
        descriptionEs: "Paquete viaja en equipaje del viajero con cobertura de seguro a Lima.",
        duration: "5-8 hours",
        durationEs: "5-8 horas",
      },
      {
        id: 3,
        icon: "Bike",
        title: "Messenger picks up from traveler",
        titleEs: "Mensajero recoge del viajero",
        description: "Local messenger meets traveler at airport or hotel to collect package.",
        descriptionEs: "Mensajero local se reúne con viajero en aeropuerto u hotel para recoger paquete.",
        duration: "30 min",
        durationEs: "30 min",
      },
      {
        id: 4,
        icon: "Home",
        title: "Messenger delivers to home",
        titleEs: "Mensajero entrega a domicilio",
        description: "Local messenger delivers package directly to recipient's home or office in Lima.",
        descriptionEs: "Mensajero local entrega paquete directamente al hogar u oficina del destinatario en Lima.",
        duration: "1-3 hours",
        durationEs: "1-3 horas",
      },
      {
        id: 5,
        icon: "CheckCircle",
        title: "Delivery confirmed",
        titleEs: "Entrega confirmada",
        description: "Recipient confirms delivery, payment distributed to traveler and messenger.",
        descriptionEs: "Destinatario confirma entrega, pago distribuido al viajero y mensajero.",
        duration: "24 hours",
        durationEs: "24 horas",
      },
    ],
  },
  {
    id: "airport-handoff",
    title: "Airport Quick Handoff",
    titleEs: "Entrega Rápida en Aeropuerto",
    description: "Fast hand-to-hand exchange at Lima airport arrival area",
    descriptionEs: "Intercambio rápido mano a mano en área de llegadas del aeropuerto de Lima",
    icon: "Zap",
    gradientClass: "bg-gradient-to-br from-pink-500/20 via-rose-500/20 to-red-500/20",
    steps: [
      {
        id: 1,
        icon: "Package",
        title: "Package shipped to traveler",
        titleEs: "Paquete enviado al viajero",
        description: "Sender ships package to traveler's Miami address ahead of flight date.",
        descriptionEs: "Remitente envía paquete a dirección del viajero en Miami antes de fecha de vuelo.",
        duration: "2-5 days",
        durationEs: "2-5 días",
      },
      {
        id: 2,
        icon: "Plane",
        title: "Traveler boards flight",
        titleEs: "Viajero aborda vuelo",
        description: "Traveler carries package in luggage. Sender receives flight number and arrival time.",
        descriptionEs: "Viajero lleva paquete en equipaje. Remitente recibe número de vuelo y hora de llegada.",
        duration: "5-8 hours",
        durationEs: "5-8 horas",
      },
      {
        id: 3,
        icon: "MapPin",
        title: "Meet at airport arrivals",
        titleEs: "Encuentro en llegadas del aeropuerto",
        description: "Recipient waits at Lima airport arrivals area. Quick meetup after customs.",
        descriptionEs: "Destinatario espera en área de llegadas del aeropuerto de Lima. Encuentro rápido después de aduana.",
        duration: "15-30 min",
        durationEs: "15-30 min",
      },
      {
        id: 4,
        icon: "CheckCircle",
        title: "Hand-to-hand exchange",
        titleEs: "Intercambio mano a mano",
        description: "Package handed directly to recipient. Both parties confirm on app. Payment released immediately.",
        descriptionEs: "Paquete entregado directamente al destinatario. Ambas partes confirman en app. Pago liberado inmediatamente.",
        duration: "5 min",
        durationEs: "5 min",
      },
    ],
  },
];
